# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vedio_key',
            new_name='video_key',
        ),
    ]
